EquestrianCenter/EquestrianCenter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' ,include('main.urls')),
    path('accounts/',include('accounts.urls'))
] + static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

EquestrianCenter/accounts/urls.py
from django.urls import path
from . import views

app_name ='accounts'

urlpatterns = [
    path("register/", views.register_user, name="register_user"),
    path("login/",views.login_user,name="login_user"),
    path("welcome/",views.welcome_page,name="welcome_page"),
    path("loged_out/",views.loged_out,name="loged_out"),
    path("logout/",views.logout_user,name="logout_user"),
    path("profile/", views.profile_user, name="profile_user"),

   
]

EquestrianCenter/main/urls.py
from django.urls import path
from .import views

app_name="main"

urlpatterns =[
    path('',views.home_page, name="home_page"),
    path('add_club/',views.add_club_page,name='add_club_page'),
    path("update_club/<club_id>/",views.update_club,name="update_club"),
    path("delete/club/<club_id>/",views.delete_club,name="delete_club"),
    path("show_club/",views.show_club_page,name="show_club_page"),
    path("details/<club_id>/", views.club_detail,name="club_detail"),
    path("review/add/<club_id>/", views.add_review,name="add_review"),
    path("book_detail/<club_id>/",views.book_detail,name="book_detail"),
    path("book/add/<club_id>/", views.book_club,name="book_club"),
    path("success/contact/",views.success_conact,name="success_contact"),
    path("success/book/",views.success_book,name="success_book"),
    path("add/comment/",views.add_comment,name="add_comment"),

]

EquestrianCenter/main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
'''Create class named Club and its objects '''
class Club(models.Model):

    PRICE_CHOICES=models.TextChoices('price',['50$',
                                              '100$',
                                              '150$',
                                              '200$',
                                              '250$',
                                              '300$',
                                              '350$',
                                              '400$',
                                              '450$'])
    
    image= models.ImageField(upload_to="images/%y/%m/%d")
    club_name= models.CharField(max_length=10)
    club_services= models.TextField()
    feature=models.TextField()
    
    open_at=models.DateTimeField()
    closed_at=models.DateTimeField()
    price= models.CharField(max_length=300,choices=PRICE_CHOICES.choices)

    def __str__(self) -> str:
        return f"{self.club_name}"
   



'''Create class Booking and its objects for user to book club '''

class Booking(models.Model):
    club=models.ForeignKey(Club,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    initial_date_time=models.DateTimeField()
    final_date_time=models.DateTimeField()

    def __str__(self) -> str:
        return f"{self.club} "
    


'''Create class named Review and its objects to review and rate clubs '''

class Review(models.Model):
    club=models.ForeignKey(Club,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    content=models.TextField()
    rating=models.FloatField()
    created_at=models.DateTimeField(auto_now_add=True)
    


'''Create class named Contact and its objects to contact with client'''

class Contact(models.Model):
     first_name=models.CharField(max_length=50)
     last_name=models.CharField(max_length=50)
     email=models.EmailField(max_length=50)
     msg=models.TextField()



'''Create class named Comment and its objects to add comment for the Equestrian Center'''


class Comment(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    content=models.TextField()
    

EquestrianCenter/main/views.py
from django.shortcuts import render,redirect
from django.http import HttpRequest,HttpResponse
from .models import Club,Review,Booking,Contact,Comment
from django.contrib.auth.models import User
from datetime import datetime



'''define home_page to display home page , top clubs ,comment and fill the form conact for every one needs help '''

def home_page(request:HttpRequest):

    top_clubs=Review.objects.filter(rating__gte=4)
    comment= Comment.objects.all()

    if request.method == "POST":
        new_contact=Contact(first_name=request.POST['first_name'],last_name=request.POST['last_name'],email=request.POST['email'],msg=request.POST['msg'])
        new_contact.save()
        return redirect('main:success_contact')
    
    return render(request,"main/home.html", {"top_clubs" : top_clubs,"comment":comment})



''' create add_club_page to make team add clubs in this Center'''

def add_club_page(request:HttpRequest):
      if request.method == "POST":
        #to add a new entry
        new_club =Club(image= request.FILES["image"], club_name = request.POST["club_name"], club_services= request.POST["club_services"],feature=request.POST["feature"],open_at=request.POST["open_at"],closed_at=request.POST["closed_at"],price=request.POST["price"])
        new_club.save()

      return render(request, "main/add_club.html")

''' create update_club to make team update clubs in this Center'''

def update_club(request : HttpRequest, club_id):

    club= Club.objects.get(id=club_id)

    if request.method == "POST":
        club.club_name= request.POST["club_name"]
        club.club_services= request.POST["club_services"]
        club.feature= request.POST["feature"]
        club.open_at= request.POST["open_at"]
        club.closed_at= request.POST["closed_at"]
        club. price= request.POST["price"]
        #to check if user chosen a file to upload for the update
        if "image" in request.FILES:
            club.image = request.FILES["image"]

        club.save()
        return redirect("main:show_club_page")

    return render(request, "main/update_club.html", {"update": club})
    
'''delete clubs only team work can do that'''
def delete_club(request : HttpRequest, club_id):
   
    club=Club.objects.get(id=club_id)
    club.delete()
    return redirect("main:home_page")

'''create show_club_page to display the clubs for user'''

def show_club_page(request:HttpRequest):
    
    show_club= Club.objects.all()
    context={"show_club":show_club}

    return render(request,"main/show_club.html",context)

''' create club_detail to delete ,update and add reviews clubs from database'''

def club_detail(request : HttpRequest, club_id):

    club= Club.objects.get(id=club_id)
    reviews =Review.objects.filter(club=club)

    return render(request,"main/club_detail.html", {"club":club,"reviews":reviews})


'''create add_review ,club in the Review model equal to club in Club model'''

def add_review(request : HttpRequest,club_id):

    if request.method == "POST":
        club = Club.objects.get(id=club_id)
        new_review = Review(user= request.user,club=club, content = request.POST["content"],rating= request.POST['rating'],created_at=request.POST.get('created_at',False))
        new_review.save()

    return redirect("main:club_detail", club_id=club_id)

'''create book_detail to fill the form and complate booking '''

def book_detail(request : HttpRequest, club_id):

    club= Club.objects.get(id=club_id)
    book =Booking.objects.filter(club=club,user= request.user)
    
    return render(request,"main/book_detail.html", {"club":club,"book":book})

'''create check_available_date to check If someone has booking at the same time '''

def check_available_date(start_date : datetime , end_date :datetime) -> bool:
    if start_date == end_date:
        return True
    else:
        return False

def book_club(request : HttpRequest,club_id):

    if request.method == "POST":
        club = Club.objects.get(id=club_id)
        new_book=Booking(user= request.user,club=club,initial_date_time= request.POST["initial_date_time"], final_date_time=request.POST["final_date_time"])
        check_time= Booking.objects.filter(initial_date_time =request.POST['initial_date_time'],final_date_time=request.POST["final_date_time"])
        if check_time:
           return render(request,"main/apologize.html")
        
        
        else: 
           new_book.save()
           return redirect('main:success_book')
    return redirect("main:book_detail", club_id=club_id)


'''If the custumer book on date not available or time '''


'''success booking'''
def success_book(request:HttpRequest):
    return render(request,"main/success_book.html")

'''success contact'''
def success_conact(request:HttpRequest):
    return render(request,"main/contact.html")



''' create add_comment to add Comment of Equestrain Center'''

def add_comment(request : HttpRequest):

    if request.method == "POST":
        comment= Comment.objects.all()
        new_comment =Comment(user= request.user, content = request.POST["content"])
        new_comment.save()

    return redirect("main:home_page")

EquestrianCenter/main/templates/main/add_club.html
{% extends 'main/home.html'%}
{% block title%}Add club{% endblock %}
{% block content %}




<div class="container" style="padding-top: 9%;">
    <div class="alert" style="background-color:burlywood;" role="alert">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h3 style="text-align:center;font-family: 'Kalam',cursive;">Add a New Club </h3>

        <div class="mt-3">
            <label>Choose File:</label>
            <input type="file" name="image" class="form-control"/>
        </div>
        <div class="mt-3">
          <label class="form-label">Club name :</label>
          <input class="form-control" name="club_name" type="text"/>
        </div>
    
        <div class="mt-3">
            <label class="form-label">club services :</label>
            <textarea class="form-control" name="club_services"></textarea>
          </div>
          <div class="mt-3">
            <label class="form-label">Features:</label>
            <textarea class="form-control" name="feature"></textarea>
          </div>
          <div class="mt-3">
          <label for="open_at"> Open at :</label>
          <input type="datetime-local" name="open_at"/>
          </div>
          <div class="mt-3">
            <label for="closed_at"> Closed at :</label>
            <input type="datetime-local" name="closed_at"/>
            </div>
          <div class="mt-3">
    <label class="form-label"><strong>Price :</strong></label>
    <select name="price" class="form-select" aria-label="Default select example">
        <option selected>Price</option>
        <option value="50$">50$</option>
        <option value="100$">100$</option>
        <option value="150$">150$</option>
        <option value="200$">200$</option>
        <option value="250$">250$</option>
        <option value="300$">300$</option>
        <option value="350$">350$</option>
        <option value="400$">400$</option>
        <option value="450$">450$</option>
      </select>
    </div>
          <br/>
          <button class="button-40" role="button" type="submit" class="btn" value="New Club"> New Club</button>
    
        
    
    </form>
    
    </div>
    </div>
  
    
    
{% endblock %}

EquestrianCenter/main/templates/main/apologize.html
{% extends 'main/home.html'%}
{% block content %}
<style>body{
    background-color: #e00b0b;
    color: #fff;
    padding-bottom: 0;
    min-height: 100%;
    font-family: 'Open Sans','Segoe UI';
    font-size: 13px;
}

.error-header {
  background: #fff;
  height: 180px;
}

.error-container {
  background: rgba(0,0,0,.05);
  text-align: center;
}

.error-container h1 {
  color:white;
}

.error-container h1 {
  font-size: 110px;
  font-weight: 300;
  margin: -103px 0 0 0;
  text-align: center;
}

.error-divider {
  margin-top: -27px;
  padding: 30px 0;
}

.error-container h2 {
  font-size: 58px;
  font-weight: 300;
  margin: 0;
  text-transform: uppercase;
}

.error-container p.description {
  color: #e5e5e5;
  font-size: 40px;
  margin: 0;
}

.return-btn, .return-btn:hover {
  border: 1px solid rgba(255,255,255,.3);
  padding: 10px 15px;
  margin-top: 100px;
  margin-bottom: 30px;
  display: inline-block;
  -webkit-border-radius: 5px;
  -webkit-background-clip: padding-box;
  -moz-border-radius: 5px;
  -moz-background-clip: padding;
  border-radius: 5px;
  background-clip: padding-box;
  color: #fff;
  font-size: 16px;
  font-weight: 300;
}

a:hover{
    text-decoration:none;    
}</style>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="error-header"> </div>
<div class="container ">
    <section class="error-container text-center">
        <h1> Apologize </h1>
        <div class="error-divider">
            <p class="description"> Sorry we can't move forward thre is a book at the same time try another time thank you..</p>
        </div>
        <a href="{% url 'main:home_page'%}" class="return-btn"><i class="fa fa-home"></i>Home</a>
    </section>
</div>
{% endblock %}

EquestrianCenter/main/templates/main/book_detail.html
{% extends 'main/home.html' %}

{% block title %}   {% endblock %}


{% block content %}


    
    <hr/>

    
    {% if request.user.is_authenticated %}



    <style>
      
    
      h1 {
      position: absolute;
      margin: 0;
      font-size: 50px;
      color: #fff;
      z-index: 2;
      line-height: 83px;
      }
      legend {
      padding: 10px;      
      font-family: Roboto, Arial, sans-serif;
      font-size: 18px;
      color: #fff;
      background-color: burlywood;
      }
      textarea {
      width: calc(100% - 12px);
      padding: 5px;
      }
      .testbox {
      display: flex;
      justify-content: center;
      align-items: center;
      height: inherit;
      padding: 20px;
      }
      form {
      width: 100%;
      padding: 20px;
      border-radius: 6px;
      background: #fff;
      box-shadow: 0 0 8px burlywood; 
      }
      .banner {
      position: relative;
      height: 250px;
      background-image: url("/uploads/media/default/0001/02/b23a2c8c49b8e43249487140e4c2e22a63bd7cb8.jpeg");  
      background-size: cover;
      display: flex;
      justify-content: center;
      align-items: center;
      text-align: center;
      }
      .banner::after {
      content: "";
      background-color: burlywood; 
      position: absolute;
      width: 100%;
      height: 100%;
      }
      input, select, textarea {
      margin-bottom: 10px;
      border: 1px solid #ccc;
      border-radius: 3px;
      }
      input {
      width: calc(100% - 10px);
      padding: 5px;
      }
      input[type="date"] {
      padding: 4px 5px;
      }
      textarea {
      width: calc(100% - 12px);
      padding: 5px;
      }
      .item:hover p, .item:hover i, .question:hover p, .question label:hover, input:hover::placeholder {
      color:  burlywood;
      }
      .item input:hover, .item select:hover, .item textarea:hover {
      border: 1px solid transparent;
      box-shadow: 0 0 3px 0  burlywood;
      color: burlywood;
      }
      .item {
      position: relative;
      margin: 10px 0;
      }
      .item span {
      color: burlywood;
      }
      input[type="date"]::-webkit-inner-spin-button {
      display: none;
      }
      .item i, input[type="date"]::-webkit-calendar-picker-indicator {
      position: absolute;
      font-size: 20px;
      color: burlywood;
      }
      .item i {
      right: 1%;
      top: 30px;
      z-index: 1;
      }
      .week {
      display:flex;
      justify-content:space-between;
      }
      .columns {
      display:flex;
      justify-content:space-between;
      flex-direction:row;
      flex-wrap:wrap;
      }
      .columns div {
      width:48%;
      }
      [type="date"]::-webkit-calendar-picker-indicator {
      right: 1%;
      z-index: 2;
      opacity: 0;
      cursor: pointer;
      }
      
      
      
      
      button:hover {
      background:  burlywood;
      }
      @media (min-width: 568px) {
      .name-item, .city-item {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
      }
      .name-item input, .name-item div {
      width: calc(50% - 20px);
      }
      .name-item div input {
      width:97%;}
      .name-item div label {
      display:block;
      padding-bottom:5px;
      }
      }
    </style>
  
    <div class="testbox" style="padding-top: 25%;">
        <form action="{% url  'main:book_club' club.id %}" method="post">
            {% csrf_token %} 
      <div class="banner">
        <h1>Booking Form</h1>
      </div>
      <br/>
      <fieldset>
        <legend>Reservation Details</legend>
        <div class="columns">
  
          <div class="item">
          <label for="initial_date_time">initial date time :<span>*</span></label>
          <input id="initial_date_time" type="datetime-local" name="initial_date_time"/>
          </div>
          <div class="item">
            <label for="final_date_time">Final date time :<span>*</span></label>
          <input id="final_date_time" type="datetime-local" name="final_date_time"/>
          </div>
          <div class="item">
          <button type="submit" value="Book Now"> Submit</button>
          </div>
      </div>
    </form>
    </div>

    

    {% else %}

    <div class="border p-3 mt-3 ">
        <p>To book please <a href="{% url 'accounts:login_user'%}">Sing In</a> or <a href="{% url 'accounts:register_user'%}">Sign Up</a></p>
    </div>

    {% endif %}



</div>


{% endblock %}

EquestrianCenter/main/templates/main/club_detail.html
{% extends 'main/home.html' %}
{% block title %}{% endblock %}
{% block content %}
<style>
body{
  font-family:poppins;
}
*{
    margin: 0px;
    padding: 0px;
    font-family: poppins;
    box-sizing: border-box;
}
a{
    text-decoration: none;
}
#testimonials{
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    width:100%;
}
.testimonial-heading{
    letter-spacing: 1px;
    margin: 30px 0px;
    padding: 10px 20px;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
}
.testimonial-heading h1{
    font-size: 2.2rem;
    font-weight: 500;
    background-color: #202020;
    color: #ffffff;
    padding: 10px 20px;
}
.testimonial-heading span{
    font-size: 1.3rem;
    color: #252525;
    margin-bottom: 10px;
    letter-spacing: 2px;
    text-transform: uppercase;
}
.testimonial-box-container{
    display: flex;
    justify-content: center;
    align-items: center;
    flex-wrap: wrap;
    width:100%;
}
.testimonial-box{
    width:500px;
    box-shadow: 2px 2px 30px rgba(0,0,0,0.1);
    background-color: #ffffff;
    padding: 20px;
    margin: 15px;
    cursor: pointer;
}
.profile-img{
    width:50px;
    height: 50px;
    border-radius: 50%;
    overflow: hidden;
    margin-right: 10px;
}
.profile-img img{
    width: 100%;
    height: 100%;
    object-fit: cover;
    object-position: center;
}
.profile{
    display: flex;
    align-items: center;
}
.name-user{
    display: flex;
    flex-direction: column;
}
.name-user strong{
    color: #3d3d3d;
    font-size: 1.1rem;
    letter-spacing: 0.5px;
}
.name-user span{
    color: #979797;
    font-size: 0.8rem;
}
.reviews{
    color: #f9d71c;
}
.box-top{
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 20px;
}
.client-comment p{
    font-size: 0.9rem;
    color: #4b4b4b;
}
.testimonial-box:hover{
    transform: translateY(-10px);
    transition: all ease 0.3s;
}
 
@media(max-width:1060px){
    .testimonial-box{
        width:45%;
        padding: 10px;
    }
}
@media(max-width:790px){
    .testimonial-box{
        width:100%;
    }
    .testimonial-heading h1{
        font-size: 1.4rem;
    }
}
@media(max-width:340px){
    .box-top{
        flex-wrap: wrap;
        margin-bottom: 10px;
    }
    .reviews{
        margin-top: 10px;
    }
}
::selection{
    color: #ffffff;
    background-color: #252525;
}</style>
<div class="container-fluid">
<div class="row">
    <div class="container-fluid" style="height:30em;width: 30em; margin-top: 3%;">
        <div class="card border-0 bg-light rounded shadow">
            <div class="card-body p-4">
                <img src="{{ club.image.url }}" class="w-100" />
                <p style="padding-top: 3%;"><strong>Club name :</strong> {{club.club_name}}</p>
                <div class="mt-3">
                    <p><strong> Services :</strong>{{club.club_services}}</p>
                    <p><strong> Features :</strong>{{club.feature}}</p>
                    <p><strong> Open at :</strong>{{club.open_at}}</p>
                    <p><strong> Closed at :</strong>{{club.closed_at}}</p>
                    <p><strong>Price :</strong> {{club.price}}</p>
                </div>
                {% if request.user.is_staff %}
                <div class="m-3 d-flex gap-2"><a href="{% url 'main:update_club' club.id %}" class="btn btn-primary">update</a><a href="{% url 'main:delete_club' club.id %}" class="btn btn-danger">delete</a></div>
                {% endif %}
                <div class="mt-3">
                </div>
            </div>
        </div>
    </div><!--end col-->
</div>
    {% if request.user.is_authenticated %}
    <div class="mt-3">
        <div>
            <form action="{% url  'main:add_review' club.id %}" method="post" style="padding-top:8%;">
                {% csrf_token %} 
     <section id="testimonials">
      <!--heading--->

      <div class="testimonial-heading" style="padding-top:20%;">
          <span>Comments</span>
          <h1>Clients Says</h1>
      </div>
      <!--testimonials-box-container------>
      <div class="testimonial-box-container">
          <!--BOX-1-------------->
          <div class="testimonial-box">
              <!--top------------------------->
              <div class="box-top">
                  <!--profile----->
                  <div class="profile">
                      <!--name-and-username-->
                      <div class="name-user">
                          <strong>Name </strong>
                          <span>Time</span>
                      </div>
                  </div>
                  <!--reviews------>
                 
              <!--Comments---------------------------------------->
              <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.2/css/all.css" />
      
              <div class="client-comment" >
                <div class="mt-3">
                <input class="form-control" name="content" type="text" placeholder="Your Review here..." />

            </div>
          </div>
          </div>
          <div class="mt-3">
            <div class="reviews">
              <div class="rating">
                <label>
                    <input type="radio" name="rating" value="1" />
                    <span class="fa fa-star icon"></span>
                  </label>
                  <label>
                    <input type="radio" name="rating" value="2" />
                    <span class="fa fa-star icon"></span>
                    <span class="fa fa-star icon"></span>
                  </label>
                  <label>
                    <input type="radio" name="rating" value="3" />
                    <span class="fa fa-star icon"></span>
                    <span class="fa fa-star icon"></span>
                    <span class="fa fa-star icon"></span>   
                  </label>
                  <label>
                    <input type="radio" name="rating" value="4" />
                    <span class="fa fa-star icon"></span>
                    <span class="fa fa-star icon"></span>
                    <span class="fa fa-star icon"></span>
                    <span class="fa fa-star icon"></span>
                  </label>
                    <input type="radio" name="rating" value="5" />
                    <span class="fa fa-star icon"></span>
                    <span class="fa fa-star icon"></span>
                    <span class="fa fa-star icon"></span>
                    <span class="fa fa-star icon"></span>
                    <span class="fa fa-star icon"></span>
                  </label>
              </div>    
            </div>
            </div>
<div class="container mt-5 pt-4">
  <div class="row align-items-end mb-4 pb-2">
                <input class="btn btn-primary mt-2" type="submit" value="Add Review" />


            </form>
      
    {% else %}

    <div class=" p-3 mt-3 fixed-bottom">
        <p>To add reveiew please <a href="{% url 'accounts:login_user'%}">Sing In</a> or <a href="{% url 'accounts:register_user'%}">Sign Up</a></p>
    </div>

    {% endif %}

</div>
<div  class=" mt-3" style="padding-top: 40%;">

  {% for review in reviews  %}
          <!--testimonials-box-container------>
          <div class="testimonial-box-container">
              <!--BOX-1-------------->
              <div class="testimonial-box">
                  <!--top------------------------->
                  <div class="box-top">
                      <!--profile----->
                      <div class="profile">
                          <!--name-and-username-->
                          <div class="name-user">
                              <strong>{{ review.user.username }}</strong>
                              <span>{{review.created_at}}</span>
                          </div>
                      </div>
                      <!--reviews------>
                      <div class="mt-3">
                        <h6>{{ review.rating }} Stars</h6>

                      </div>
                  <!--Comments---------------------------------------->
                
                  <div class="client-comment" >
                    <div class="mt-3">
                    <p class="form-control" >{{ review.content }}</p>
                  </p>
                  </div>
              </div>
              </div>
    
      </div>
  {% endfor %}
</div>


{% endblock %}

EquestrianCenter/main/templates/main/contact.html
{% extends 'main/home.html'%}
{% block title %}{% endblock %}
{%block content %}
<style>
body{margin-top:20px;}
.mail-seccess {
    text-align: center;
	background: #fff;
	border-top: 1px solid #eee;
}
.mail-seccess .success-inner {
	display: inline-block;
}
.mail-seccess .success-inner h1 {
	font-size: 100px;
	text-shadow: 3px 5px 2px #3333;
	color: #006DFE;
	font-weight: 700;
}
.mail-seccess .success-inner h1 span {
	display: block;
	font-size: 25px;
	color: #333;
	font-weight: 600;
	text-shadow: none;
	margin-top: 20px;
}
.mail-seccess .success-inner p {
	padding: 20px 15px;
}
.mail-seccess .success-inner .btn{
	color:#fff;
}
</style>

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
<section class="mail-seccess section">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 offset-lg-3 col-12">
				<!-- Error Inner -->
				<div class="success-inner">
					<h1><i class="fa fa-envelope"></i><span>Your Mail Sent Successfully!</span></h1>
					<p>We will contact you soon...</p>
					<a href="{% url 'main:home_page'%}" class="btn btn-primary btn-lg">Go Home</a>
				</div>
				<!--/ End Error Inner -->
			</div>
		</div>
	</div>
</section>
{% endblock %}

EquestrianCenter/main/templates/main/success_book.html
{% extends 'main/home.html'%}
{% block content %}
<style>body{
    background-color: green;
    color: #fff;
    padding-bottom: 0;
    min-height: 100%;
    font-family: 'Open Sans','Segoe UI';
    font-size: 13px;
}

.error-header {
  background: #fff;
  height: 180px;
}

.error-container {
  background: rgba(0,0,0,.05);
  text-align: center;
}

.error-container h1 {
  color:white;
}

.error-container h1 {
  font-size: 110px;
  font-weight: 300;
  margin: -103px 0 0 0;
  text-align: center;
}

.error-divider {
  margin-top: -27px;
  padding: 30px 0;
}

.error-container h2 {
  font-size: 58px;
  font-weight: 300;
  margin: 0;
  text-transform: uppercase;
}

.error-container p.description {
  color: #e5e5e5;
  font-size: 40px;
  margin: 0;
}

.return-btn, .return-btn:hover {
  border: 1px solid rgba(255,255,255,.3);
  padding: 10px 15px;
  margin-top: 100px;
  margin-bottom: 30px;
  display: inline-block;
  -webkit-border-radius: 5px;
  -webkit-background-clip: padding-box;
  -moz-border-radius: 5px;
  -moz-background-clip: padding;
  border-radius: 5px;
  background-clip: padding-box;
  color: #fff;
  font-size: 16px;
  font-weight: 300;
}

a:hover{
    text-decoration:none;    
}</style>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="error-header"> </div>
<div class="container ">
    <section class="error-container text-center">
        <h1> Congrats </h1>
        <div class="error-divider">
            <p class="description"> Your request has been send successfuly ...</p>
        </div>
        <a href="{% url 'main:home_page'%}" class="return-btn"><i class="fa fa-home"></i>Home</a>
    </section>
</div>
{% endblock %}